### ISSUE TITLE
Replace build_byte_string() with bytes.fromhex()

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/chewie#73]
Does anyone have any objection to me submitting a PR that replaces netils.build_byte_string with bytes.fromhex()?

There's no need to support Python 2.x, and bytes.fromhex() will do the right thing.

netils.build_byte_string doesn't deal with certain edge cases correctly...

```
>>> import netils
>>> netils.build_byte_string("123")
b'\x12'
>>> netils.build_byte_string("12 3")
b'\x12\x03'
```

Thanks.

**Comment by samrussell** [comment]
netils was a means to an end, kill it with fire!

**Comment by Bairdo** [comment]
close? #74
