### ISSUE TITLE
Exception handling with MessageParser

### ISSUE THREAD

**Issue by Bairdo** [faucetsdn/chewie#88]
There are times we raise exceptions during packet parsing which should result in the processed packet being dropped, and Chewie can safely continue processing other packets.

Exceptions (and example of when raised) include:
- KeyError: unknown EAP type.
- UnicodeDecodeError: Illegal bytes in the EAP.identity field.
- ValueError: unknown EAP code.
- struct.error: the payload doesn't contain enough bytes to unpack.

Should all of these be caught by the caller, or a new exception created (e.g. InvalidPacketException)?
A new exception can still contain the original reason.

Problem if we catch them all, the same exception could be raised somewhere else, that we might not expect (e.g. KeyError & ValueError are reasonably common errors for other parts of python to raise with) and it will basically be swallowed.

Does anyone have any thoughts on this?

**Comment by samrussell** [comment]
I'd make it clear that the parser throws this and then catch that one
custom exception in Chewie - that way anything unexpected still crashes the
app. Just use a different message or ID as metadata so we can log that, or
even store the exception trace in the exception

Also consider that the issues could be different between the Radius and EAP
parsers - they are doing different jobs so don't worry if the interface
differs for them.

**Comment by byllyfish** [comment]
Having the MessageParser API throw a MessageParseError makes sense to me. It should be part of the documented contract of each 'parse' method:

```python
class MessageParser:

    @staticmethod
    def eap_parse(data, src_mac):
        """Parse the EAP payload.

        Args:
            data (bytes): ...
            src_mac (MacAddress): ...
        Returns:
            EapMessage subclass
        Raises:
            MessageParseError: if there's a parse error
        """
```

The easiest way to do this would be to catch the exceptions you listed in eap_parse and re-raise the new exception.

**Comment by samrussell** [comment]
Bill touched on a good point - catch the exceptions you've listed (i.e. no
catch-all inside the parser), or do some explicit sanity checking and
proactively raise exceptions based on that
