### ISSUE TITLE
support for switches with OF port numbers > 255

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/chewie#98]
A vendor reports that they use a chassis slot number based scheme to assign OF port numbers, so they have a switch with OF port numbers > 255. It would be good to support 2 bytes worth of OF port.

**Comment by gizmoguy** [comment]
Error message is: "New config bad (802.1x not supported on ports > 255) - rejecting"

@Bairdo is that something you added?

**Comment by Bairdo** [comment]
yea I added that. I was using one byte of the mac address to represent the dp, and another for the port. I'll update it so 2 for port. Will that be enough?

**Comment by anarkiwi** [comment]
Famous last words, that should be enough...
